/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mini.toko.atk.view;

import com.mini.toko.atk.controller.TokoAtkController;
import java.awt.Color;

/**
 *
 * @author Bhaskara
 */
public class TokoView extends javax.swing.JFrame {
    
    

    /**
     * @return the txtHargaBarang
     */
    public javax.swing.JTextField getTxtHargaBarang() {
        return txtHargaBarang;
    }

    /**
     * @param txtHargaBarang the txtHargaBarang to set
     */
    public void setTxtHargaBarang(javax.swing.JTextField txtHargaBarang) {
        this.txtHargaBarang = txtHargaBarang;
    }

    /**
     * @return the txtJenisBarang
     */
    public javax.swing.JTextField getTxtJenisBarang() {
        return txtJenisBarang;
    }

    /**
     * @param txtJenisBarang the txtJenisBarang to set
     */
    public void setTxtJenisBarang(javax.swing.JTextField txtJenisBarang) {
        this.txtJenisBarang = txtJenisBarang;
    }

    /**
     * @return the txtKodeBarang
     */
    public javax.swing.JTextField getTxtKodeBarang() {
        return txtKodeBarang;
    }

    /**
     * @param txtKodeBarang the txtKodeBarang to set
     */
    public void setTxtKodeBarang(javax.swing.JTextField txtKodeBarang) {
        this.txtKodeBarang = txtKodeBarang;
    }

    /**
     * @return the txtMerkBarang
     */
    public javax.swing.JTextField getTxtMerkBarang() {
        return txtMerkBarang;
    }

    /**
     * @param txtMerkBarang the txtMerkBarang to set
     */
    public void setTxtMerkBarang(javax.swing.JTextField txtMerkBarang) {
        this.txtMerkBarang = txtMerkBarang;
    }

    /**
     * @return the txtNamaBarang
     */
    public javax.swing.JTextField getTxtNamaBarang() {
        return txtNamaBarang;
    }

    /**
     * @param txtNamaBarang the txtNamaBarang to set
     */
    public void setTxtNamaBarang(javax.swing.JTextField txtNamaBarang) {
        this.txtNamaBarang = txtNamaBarang;
    }

    /**
     * @return the txtStokBarang
     */
    public javax.swing.JTextField getTxtStokBarang() {
        return txtStokBarang;
    }

    /**
     * @param txtStokBarang the txtStokBarang to set
     */
    public void setTxtStokBarang(javax.swing.JTextField txtStokBarang) {
        this.txtStokBarang = txtStokBarang;
    }
    
    public final TokoAtkController tokoAtkController = new TokoAtkController(this);
    
    public TokoView() {
        initComponents();
        tokoAtkController.getAllData();
        jPanel1.setBackground(new Color(0,0,0,0));
    }

    /**
     * @return the tblToko
     */
    public javax.swing.JTable getTblToko() {
        return tblToko;
    }

    /**
     * @param tblToko the tblToko to set
     */
    public void setTblToko(javax.swing.JTable tblToko) {
        this.tblToko = tblToko;
    }

    

    /**
     * Creates new form TokoView
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtKodeBarang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNamaBarang = new javax.swing.JTextField();
        txtMerkBarang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtJenisBarang = new javax.swing.JTextField();
        txtStokBarang = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblToko = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtHargaBarang = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Toko ATK");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 13, 620, 60));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Kode barang");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));
        getContentPane().add(txtKodeBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 126, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nama Barang");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 106, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Merk Barang");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 20));
        getContentPane().add(txtNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 126, -1));
        getContentPane().add(txtMerkBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 126, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Jenis Barang");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Stok");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, 20));
        getContentPane().add(txtJenisBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 157, -1));
        getContentPane().add(txtStokBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 157, -1));

        tblToko.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblToko.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTokoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblToko);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 600, 130));

        btnSimpan.setText("Simpan");
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, 30));

        btnDelete.setText("Delete");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, 30));

        btnUpdate.setText("Update");
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, 30));

        btnClear.setText("Clear");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, -1, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Harga");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        txtHargaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaBarangActionPerformed(evt);
            }
        });
        getContentPane().add(txtHargaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 157, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 350));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/765b707111cc0e1.jpg_wh860.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-240, 0, 860, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        tokoAtkController.saveToko();
    }//GEN-LAST:event_btnSimpanMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        tokoAtkController.deleteToko();
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        tokoAtkController.updateToko();
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        tokoAtkController.clear();
    }//GEN-LAST:event_btnClearMouseClicked

    private void tblTokoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTokoMouseClicked
        tokoAtkController.getData();
    }//GEN-LAST:event_tblTokoMouseClicked

    private void txtHargaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaBarangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TokoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TokoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TokoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TokoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TokoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblToko;
    private javax.swing.JTextField txtHargaBarang;
    private javax.swing.JTextField txtJenisBarang;
    private javax.swing.JTextField txtKodeBarang;
    private javax.swing.JTextField txtMerkBarang;
    private javax.swing.JTextField txtNamaBarang;
    private javax.swing.JTextField txtStokBarang;
    // End of variables declaration//GEN-END:variables
}
